name: Chuck Norris test workflow

on:
  workflow_dispatch:

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: chuck-norris-quote-action
        uses: ./.github/actions/chuck-norris-quote

      - name: chuck-norris-quote-action-text
        id: textchuck
        uses: ./.github/actions/chuck-norris-quote
        with:
          quote-format: 'text'

      - name: ShowTextOutput
        run: echo "${{ steps.textchuck.outputs.quote }}"

      - name: chuck-norris-quote-action-markdown
        id: markdownchuck
        uses: ./.github/actions/chuck-norris-quote
        with:
          quote-format: 'markdown'

      - name: ShowMarkdownOutput
        run: echo '${{ steps.markdownchuck.outputs.quote }}'

      - name: chuck-norris-quote-action-html
        id: htmlchuck
        uses: ./.github/actions/chuck-norris-quote
        with:
          quote-format: 'html'
      
      - name: ShowHtmlOutput
        run: echo '${{ steps.htmlchuck.outputs.quote }}'
