name: Chuck Norris test workflow

on:
  workflow_dispatch:
  pull_request:
    

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: chuck-norris-quote-action
        uses: glav/chuck-norris-quote

      - name: chuck-norris-quote-action-text
        id: textchuck
        uses: glav/chuck-norris-quote
        with:
          quote-format: 'text'
          escape-quote: 'true'

      - name: ShowTextOutput
        run: echo "${{ steps.textchuck.outputs.quote }}"


